// This file is part of the Luau programming language and is licensed under MIT License; see LICENSE.txt for details
// Copyright (c) 2026 Júlia Klee, Roblox Corporation, Lua.org/PUC-Rio. MIT License.
#include "Luau/SingleBinaryCompiler.h"

#include "Luau/Ast.h"
#include "Luau/CodeGen.h"
#include "Luau/CodeGenOptions.h"
#include "Luau/Compiler.h"
#include "Luau/FileUtils.h"
#include "Luau/Parser.h"
#include "Luau/Require.h"
#include "Luau/VfsNavigator.h"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <memory>
#include <queue>
#include <set>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

#if !defined(_WIN32)
#include <unistd.h>
#include <sys/wait.h>
#else
#include <windows.h>
#include <process.h> // _getpid()
#define getpid _getpid
#endif

namespace Luau
{

namespace
{

struct DiscoveredModule
{
    std::string chunkName;
    std::string loadName;
    std::string absolutePath;
    std::string source;
    std::string bytecode;
};

struct DiscoveredAsset
{
    std::string path;
    std::string relativePath;
    std::string absolutePath;
    std::string data;
};

class RequireVisitor : public AstVisitor
{
public:
    std::vector<std::string> requirePaths;

    bool visit(AstExprCall* call) override
    {
        if (AstExprGlobal* global = call->func->as<AstExprGlobal>())
        {
            if (global->name == "require" && call->args.size == 1)
            {
                if (AstExprConstantString* str = call->args.data[0]->as<AstExprConstantString>())
                {
                    requirePaths.emplace_back(str->value.data, str->value.size);
                }
            }
        }
        return true;
    }
};

std::string formatHexBytes(const std::string& data)
{
    std::ostringstream oss;
    oss << "{";
    for (size_t i = 0; i < data.size(); ++i)
    {
        if (i % 16 == 0)
            oss << "\n    ";
        char buf[8];
        snprintf(buf, sizeof(buf), "0x%02x, ", static_cast<unsigned char>(data[i]));
        oss << buf;
    }
    if (!data.empty())
        oss << "\n";
    oss << "}";
    return oss.str();
}

std::string escapeCString(const std::string& str)
{
    std::string result;
    for (char c : str)
    {
        if (c == '\\')
            result += "\\\\";
        else if (c == '\"')
            result += "\\\"";
        else if (c == '\n')
            result += "\\n";
        else if (c == '\r')
            result += "\\r";
        else if (c == '\t')
            result += "\\t";
        else
            result += c;
    }
    return result;
}

std::string generateRunnerCpp(
    const std::vector<DiscoveredModule>& modules,
    size_t entryIndex,
    const std::vector<DiscoveredAsset>& assets,
    bool enableCodegen,
    int optimizationLevel,
    int debugLevel
)
{
    std::ostringstream out;

    out << "// Auto-generated by Jaci Single Binary Compiler\n";
    out << "// Copyright (c) 2026 Júlia Klee, Roblox Corporation, Lua.org/PUC-Rio. MIT License.\n\n";

    out << "#include \"lua.h\"\n";
    out << "#include \"lualib.h\"\n";
    out << "#include \"Luau/CodeGen.h\"\n";
    out << "#include \"Luau/Compiler.h\"\n";
    out << "#include \"Luau/Require.h\"\n";
    out << "#include \"Luau/VfsNavigator.h\"\n";
    out << "#include \"Luau/FileUtils.h\"\n";
    out << "#include \"Luau/ReplRequirer.h\"\n\n";
    out << "#include <cstdio>\n";
    out << "#include <cstdlib>\n";
    out << "#include <cstring>\n";
    out << "#include <string>\n";
    out << "#include <string_view>\n";
    out << "#include <vector>\n\n";

    // Embed bytecode arrays for modules
    for (size_t i = 0; i < modules.size(); ++i)
    {
        out << "static const unsigned char kModuleData_" << i << "[] = "
            << formatHexBytes(modules[i].bytecode) << ";\n\n";
    }

    out << "struct EmbeddedModuleRecord\n{\n";
    out << "    const char* chunkName;\n";
    out << "    const char* loadName;\n";
    out << "    const char* absolutePath;\n";
    out << "    const unsigned char* bytecode;\n";
    out << "    size_t bytecodeSize;\n";
    out << "};\n\n";

    out << "static const EmbeddedModuleRecord kEmbeddedModules[] = {\n";
    for (size_t i = 0; i < modules.size(); ++i)
    {
        out << "    { \"" << escapeCString(modules[i].chunkName) << "\", \""
            << escapeCString(modules[i].loadName) << "\", \""
            << escapeCString(modules[i].absolutePath) << "\", "
            << "kModuleData_" << i << ", "
            << modules[i].bytecode.size() << " },\n";
    }
    out << "};\n";
    out << "static const size_t kNumEmbeddedModules = " << modules.size() << ";\n";
    out << "static const size_t kEntryModuleIndex = " << entryIndex << ";\n\n";

    // Embed asset data arrays
    for (size_t i = 0; i < assets.size(); ++i)
    {
        out << "static const unsigned char kAssetData_" << i << "[] = "
            << formatHexBytes(assets[i].data) << ";\n\n";
    }

    out << "struct EmbeddedAssetRecord\n{\n";
    out << "    const char* path;\n";
    out << "    const char* relativePath;\n";
    out << "    const char* absolutePath;\n";
    out << "    const unsigned char* data;\n";
    out << "    size_t size;\n";
    out << "};\n\n";

    out << "static const EmbeddedAssetRecord kEmbeddedAssets[] = {\n";
    for (size_t i = 0; i < assets.size(); ++i)
    {
        out << "    { \"" << escapeCString(assets[i].path) << "\", \""
            << escapeCString(assets[i].relativePath) << "\", \""
            << escapeCString(assets[i].absolutePath) << "\", "
            << "kAssetData_" << i << ", "
            << assets[i].data.size() << " },\n";
    }
    out << "};\n";
    out << "static const size_t kNumEmbeddedAssets = " << assets.size() << ";\n\n";

    out << "static const EmbeddedAssetRecord* findEmbeddedAsset(const char* name)\n{\n";
    out << "    if (!name || !*name || kNumEmbeddedAssets == 0) return nullptr;\n";
    out << "    std::string_view target(name);\n";
    out << "    if (target.size() >= 2 && target[0] == '.' && (target[1] == '/' || target[1] == '\\\\'))\n";
    out << "        target.remove_prefix(2);\n\n";
    out << "    for (size_t i = 0; i < kNumEmbeddedAssets; ++i)\n    {\n";
    out << "        std::string_view p = kEmbeddedAssets[i].path;\n";
    out << "        if (p.size() >= 2 && p[0] == '.' && (p[1] == '/' || p[1] == '\\\\')) p.remove_prefix(2);\n";
    out << "        std::string_view rp = kEmbeddedAssets[i].relativePath;\n";
    out << "        if (rp.size() >= 2 && rp[0] == '.' && (rp[1] == '/' || rp[1] == '\\\\')) rp.remove_prefix(2);\n";
    out << "        if (target == p || target == rp || target == kEmbeddedAssets[i].absolutePath)\n";
    out << "            return &kEmbeddedAssets[i];\n";
    out << "    }\n";
    out << "    for (size_t i = 0; i < kNumEmbeddedAssets; ++i)\n    {\n";
    out << "        std::string_view absPath(kEmbeddedAssets[i].absolutePath);\n";
    out << "        if (absPath.size() >= target.size() && absPath.substr(absPath.size() - target.size()) == target)\n";
    out << "            return &kEmbeddedAssets[i];\n";
    out << "    }\n";
    out << "    return nullptr;\n";
    out << "}\n\n";

    out << "static const EmbeddedModuleRecord* findEmbeddedModule(const char* name)\n{\n";
    out << "    if (!name) return nullptr;\n";
    out << "    std::string_view target(name);\n";
    out << "    if (!target.empty() && target[0] == '@')\n";
    out << "        target.remove_prefix(1);\n\n";
    out << "    for (size_t i = 0; i < kNumEmbeddedModules; ++i)\n    {\n";
    out << "        std::string_view chunk = kEmbeddedModules[i].chunkName;\n";
    out << "        if (!chunk.empty() && chunk[0] == '@') chunk.remove_prefix(1);\n";
    out << "        if (target == chunk || target == kEmbeddedModules[i].loadName || target == kEmbeddedModules[i].absolutePath)\n";
    out << "            return &kEmbeddedModules[i];\n";
    out << "    }\n";
    out << "    for (size_t i = 0; i < kNumEmbeddedModules; ++i)\n    {\n";
    out << "        std::string_view absPath(kEmbeddedModules[i].absolutePath);\n";
    out << "        if (absPath.size() >= target.size() && absPath.substr(absPath.size() - target.size()) == target)\n";
    out << "            return &kEmbeddedModules[i];\n";
    out << "    }\n";
    out << "    return nullptr;\n";
    out << "}\n\n";

    out << "/// Embedded require configuration\n";
    out << "struct EmbeddedRequireContext\n{\n";
    out << "    std::string currentPath;\n";
    out << "    const EmbeddedModuleRecord* currentModule = nullptr;\n";
    out << "};\n\n";

    out << "static bool embedded_is_require_allowed(lua_State* L, void* ctx, const char* requirer_chunkname)\n{\n";
    out << "    return true;\n";
    out << "}\n\n";

    out << "static luarequire_NavigateResult embedded_reset(lua_State* L, void* ctx, const char* requirer_chunkname)\n{\n";
    out << "    EmbeddedRequireContext* req = static_cast<EmbeddedRequireContext*>(ctx);\n";
    out << "    if (!requirer_chunkname) return NAVIGATE_NOT_FOUND;\n";
    out << "    std::string name = requirer_chunkname;\n";
    out << "    if (!name.empty() && name[0] == '@')\n";
    out << "        name = name.substr(1);\n";
    out << "    req->currentPath = name;\n";
    out << "    req->currentModule = findEmbeddedModule(name.c_str());\n";
    out << "    return NAVIGATE_SUCCESS;\n";
    out << "}\n\n";

    out << "static luarequire_NavigateResult embedded_jump_to_alias(lua_State* L, void* ctx, const char* path)\n{\n";
    out << "    EmbeddedRequireContext* req = static_cast<EmbeddedRequireContext*>(ctx);\n";
    out << "    if (!path) return NAVIGATE_NOT_FOUND;\n";
    out << "    req->currentPath = path;\n";
    out << "    req->currentModule = findEmbeddedModule(path);\n";
    out << "    return NAVIGATE_SUCCESS;\n";
    out << "}\n\n";

    out << "static luarequire_NavigateResult embedded_to_parent(lua_State* L, void* ctx)\n{\n";
    out << "    EmbeddedRequireContext* req = static_cast<EmbeddedRequireContext*>(ctx);\n";
    out << "    req->currentModule = nullptr;\n";
    out << "    size_t slash = req->currentPath.find_last_of('/');\n";
    out << "    if (slash == std::string::npos || slash == 0)\n";
    out << "        return NAVIGATE_NOT_FOUND;\n";
    out << "    req->currentPath = req->currentPath.substr(0, slash);\n";
    out << "    return NAVIGATE_SUCCESS;\n";
    out << "}\n\n";

    out << "static luarequire_NavigateResult embedded_to_child(lua_State* L, void* ctx, const char* name)\n{\n";
    out << "    EmbeddedRequireContext* req = static_cast<EmbeddedRequireContext*>(ctx);\n";
    out << "    req->currentModule = nullptr;\n";
    out << "    if (!name) return NAVIGATE_NOT_FOUND;\n";
    out << "    if (req->currentPath.empty() || req->currentPath.back() == '/')\n";
    out << "        req->currentPath += name;\n";
    out << "    else\n";
    out << "        req->currentPath += std::string(\"/\") + name;\n";
    out << "    return NAVIGATE_SUCCESS;\n";
    out << "}\n\n";

    out << "static bool embedded_is_module_present(lua_State* L, void* ctx)\n{\n";
    out << "    EmbeddedRequireContext* req = static_cast<EmbeddedRequireContext*>(ctx);\n";
    out << "    if (req->currentModule) return true;\n";
    out << "    const std::string& p = req->currentPath;\n";
    out << "    if (findEmbeddedModule(p.c_str()) ||\n";
    out << "        findEmbeddedModule((p + \".luau\").c_str()) ||\n";
    out << "        findEmbeddedModule((p + \".lua\").c_str()) ||\n";
    out << "        findEmbeddedModule((p + \"/init.luau\").c_str()) ||\n";
    out << "        findEmbeddedModule((p + \"/init.lua\").c_str()) ||\n";
    out << "        findEmbeddedModule((p + \"/index.luau\").c_str()) ||\n";
    out << "        findEmbeddedModule((p + \"/index.lua\").c_str()) ||\n";
    out << "        findEmbeddedAsset(p.c_str()))\n";
    out << "    {\n";
    out << "        return true;\n";
    out << "    }\n";
    out << "    return isFile(p);\n";
    out << "}\n\n";

    out << "static luarequire_WriteResult embedded_get_chunkname(lua_State* L, void* ctx, char* buffer, size_t buffer_size, size_t* size_out)\n{\n";
    out << "    EmbeddedRequireContext* req = static_cast<EmbeddedRequireContext*>(ctx);\n";
    out << "    std::string name = \"@\" + req->currentPath;\n";
    out << "    size_t sz = name.size() + 1;\n";
    out << "    if (buffer_size < sz) { *size_out = sz; return luarequire_WriteResult::WRITE_BUFFER_TOO_SMALL; }\n";
    out << "    *size_out = sz;\n";
    out << "    memcpy(buffer, name.c_str(), sz);\n";
    out << "    return luarequire_WriteResult::WRITE_SUCCESS;\n";
    out << "}\n\n";

    out << "static luarequire_WriteResult embedded_get_loadname(lua_State* L, void* ctx, char* buffer, size_t buffer_size, size_t* size_out)\n{\n";
    out << "    EmbeddedRequireContext* req = static_cast<EmbeddedRequireContext*>(ctx);\n";
    out << "    std::string name = req->currentPath;\n";
    out << "    size_t sz = name.size() + 1;\n";
    out << "    if (buffer_size < sz) { *size_out = sz; return luarequire_WriteResult::WRITE_BUFFER_TOO_SMALL; }\n";
    out << "    *size_out = sz;\n";
    out << "    memcpy(buffer, name.c_str(), sz);\n";
    out << "    return luarequire_WriteResult::WRITE_SUCCESS;\n";
    out << "}\n\n";

    out << "static luarequire_WriteResult embedded_get_cache_key(lua_State* L, void* ctx, char* buffer, size_t buffer_size, size_t* size_out)\n{\n";
    out << "    return embedded_get_loadname(L, ctx, buffer, buffer_size, size_out);\n";
    out << "}\n\n";

    out << "static luarequire_ConfigStatus embedded_get_config_status(lua_State* L, void* ctx)\n{\n";
    out << "    return CONFIG_ABSENT;\n";
    out << "}\n\n";

    out << "static luarequire_WriteResult embedded_get_config(lua_State* L, void* ctx, char* buffer, size_t buffer_size, size_t* size_out)\n{\n";
    out << "    return luarequire_WriteResult::WRITE_FAILURE;\n";
    out << "}\n\n";

    out << "static luarequire_NavigateResult embedded_alias_fallback(lua_State* L, void* ctx, const char* aliasUnprefixed)\n{\n";
    out << "    EmbeddedRequireContext* req = static_cast<EmbeddedRequireContext*>(ctx);\n";
    out << "    if (!aliasUnprefixed) return NAVIGATE_NOT_FOUND;\n";
    out << "    static const char* kPkgDirs[] = {\"luau_packages\", \"packages\", \"node_modules\"};\n";
    out << "    for (const char* dir : kPkgDirs)\n    {\n";
    out << "        std::string cand = std::string(dir) + \"/\" + aliasUnprefixed;\n";
    out << "        if (findEmbeddedModule(cand.c_str()) ||\n";
    out << "            findEmbeddedModule((cand + \".luau\").c_str()) ||\n";
    out << "            findEmbeddedModule((cand + \"/init.luau\").c_str()))\n";
    out << "        {\n";
    out << "            req->currentPath = cand;\n";
    out << "            return NAVIGATE_SUCCESS;\n";
    out << "        }\n";
    out << "    }\n";
    out << "    return NAVIGATE_NOT_FOUND;\n";
    out << "}\n\n";

    out << "static int embedded_load(lua_State* L, void* ctx, const char* path, const char* chunkname, const char* loadname)\n{\n";
    out << "    lua_State* GL = lua_mainthread(L);\n";
    out << "    lua_State* ML = lua_newthread(GL);\n";
    out << "    lua_xmove(GL, L, 1);\n";
    out << "    luaL_sandboxthread(ML);\n\n";
    out << "    const EmbeddedModuleRecord* mod = findEmbeddedModule(loadname);\n";
    out << "    if (!mod) mod = findEmbeddedModule(chunkname);\n";
    out << "    if (!mod) mod = findEmbeddedModule(path);\n";
    out << "    if (!mod && loadname)\n";
    out << "    {\n";
    out << "        std::string s(loadname);\n";
    out << "        mod = findEmbeddedModule((s + \".luau\").c_str());\n";
    out << "        if (!mod) mod = findEmbeddedModule((s + \".lua\").c_str());\n";
    out << "        if (!mod) mod = findEmbeddedModule((s + \"/init.luau\").c_str());\n";
    out << "        if (!mod) mod = findEmbeddedModule((s + \"/init.lua\").c_str());\n";
    out << "        if (!mod) mod = findEmbeddedModule((s + \"/index.luau\").c_str());\n";
    out << "        if (!mod) mod = findEmbeddedModule((s + \"/index.lua\").c_str());\n";
    out << "    }\n\n";
    out << "    int status = LUA_OK;\n";
    out << "    if (mod)\n    {\n";
    out << "        status = luau_load(ML, chunkname, reinterpret_cast<const char*>(mod->bytecode), mod->bytecodeSize, 0);\n";
    out << "    }\n    else\n    {\n";
    out << "        const EmbeddedAssetRecord* asset = findEmbeddedAsset(loadname);\n";
    out << "        if (!asset) asset = findEmbeddedAsset(path);\n";
    out << "        if (asset)\n        {\n";
    out << "            Luau::CompileOptions copts;\n";
    out << "            copts.optimizationLevel = " << optimizationLevel << ";\n";
    out << "            copts.debugLevel = " << debugLevel << ";\n";
    out << "            std::string bytecode = Luau::compile(std::string(reinterpret_cast<const char*>(asset->data), asset->size), copts);\n";
    out << "            status = luau_load(ML, chunkname, bytecode.data(), bytecode.size(), 0);\n";
    out << "        }\n        else\n        {\n";
    out << "            std::optional<std::string> contents = readFile(loadname);\n";
    out << "            if (!contents) luaL_error(L, \"could not read module '%s'\", loadname);\n";
    out << "            Luau::CompileOptions copts;\n";
    out << "            copts.optimizationLevel = " << optimizationLevel << ";\n";
    out << "            copts.debugLevel = " << debugLevel << ";\n";
    out << "            std::string bytecode = Luau::compile(*contents, copts);\n";
    out << "            status = luau_load(ML, chunkname, bytecode.data(), bytecode.size(), 0);\n";
    out << "        }\n";
    out << "    }\n\n";
    out << "    if (status != 0) luaL_error(L, \"failed to load module '%s'\", loadname);\n\n";
    if (enableCodegen)
    {
        out << "    Luau::CodeGen::CompilationOptions nativeOptions;\n";
        out << "    Luau::CodeGen::compile(ML, -1, nativeOptions);\n\n";
    }
    out << "    status = lua_resume(ML, L, 0);\n";
    out << "    if (status == 0)\n    {\n";
    out << "        if (lua_gettop(ML) != 1) luaL_error(L, \"module must return a single value\");\n";
    out << "    }\n    else if (status == LUA_YIELD)\n    {\n";
    out << "        luaL_error(L, \"module can not yield\");\n";
    out << "    }\n    else\n    {\n";
    out << "        luaL_error(L, \"error running module: %s\", lua_isstring(ML, -1) ? lua_tostring(ML, -1) : \"unknown\");\n";
    out << "    }\n\n";
    out << "    lua_xmove(ML, L, 1);\n";
    out << "    lua_remove(L, -2);\n";
    out << "    return 1;\n";
    out << "}\n\n";

    out << "static void embeddedRequireConfigInit(luarequire_Configuration* config)\n{\n";
    out << "    config->is_require_allowed = embedded_is_require_allowed;\n";
    out << "    config->reset = embedded_reset;\n";
    out << "    config->jump_to_alias = embedded_jump_to_alias;\n";
    out << "    config->to_parent = embedded_to_parent;\n";
    out << "    config->to_child = embedded_to_child;\n";
    out << "    config->is_module_present = embedded_is_module_present;\n";
    out << "    config->get_config_status = embedded_get_config_status;\n";
    out << "    config->get_chunkname = embedded_get_chunkname;\n";
    out << "    config->get_loadname = embedded_get_loadname;\n";
    out << "    config->get_cache_key = embedded_get_cache_key;\n";
    out << "    config->get_config = embedded_get_config;\n";
    out << "    config->load = embedded_load;\n";
    out << "    config->to_alias_fallback = embedded_alias_fallback;\n";
    out << "}\n\n";

    // Embedded FS Interception Helpers
    out << "static int embedded_fs_readfile(lua_State* L)\n{\n";
    out << "    const char* pathStr = luaL_checkstring(L, 1);\n";
    out << "    const EmbeddedAssetRecord* asset = findEmbeddedAsset(pathStr);\n";
    out << "    if (asset)\n    {\n";
    out << "        lua_pushlstring(L, reinterpret_cast<const char*>(asset->data), asset->size);\n";
    out << "        return 1;\n";
    out << "    }\n";
    out << "    std::optional<std::string> fileData = readFile(pathStr);\n";
    out << "    if (!fileData) luaL_error(L, \"fs.readfile: cannot open file: %s\", pathStr);\n";
    out << "    lua_pushlstring(L, fileData->data(), fileData->size());\n";
    out << "    return 1;\n";
    out << "}\n\n";

    out << "static int embedded_fs_exists(lua_State* L)\n{\n";
    out << "    const char* pathStr = luaL_checkstring(L, 1);\n";
    out << "    if (findEmbeddedAsset(pathStr)) { lua_pushboolean(L, 1); return 1; }\n";
    out << "    lua_pushboolean(L, isFile(pathStr) || isDirectory(pathStr));\n";
    out << "    return 1;\n";
    out << "}\n\n";

    out << "static int embedded_fs_isfile(lua_State* L)\n{\n";
    out << "    const char* pathStr = luaL_checkstring(L, 1);\n";
    out << "    if (findEmbeddedAsset(pathStr)) { lua_pushboolean(L, 1); return 1; }\n";
    out << "    lua_pushboolean(L, isFile(pathStr));\n";
    out << "    return 1;\n";
    out << "}\n\n";

    out << "static int embedded_fs_isdir(lua_State* L)\n{\n";
    out << "    const char* pathStr = luaL_checkstring(L, 1);\n";
    out << "    std::string prefix(pathStr);\n";
    out << "    if (prefix.size() >= 2 && prefix[0] == '.' && (prefix[1] == '/' || prefix[1] == '\\\\')) prefix = prefix.substr(2);\n";
    out << "    if (!prefix.empty() && prefix.back() != '/' && prefix.back() != '\\\\') prefix += '/';\n";
    out << "    for (size_t i = 0; i < kNumEmbeddedAssets; ++i)\n    {\n";
    out << "        std::string_view p = kEmbeddedAssets[i].relativePath;\n";
    out << "        if (p.size() >= 2 && p[0] == '.' && (p[1] == '/' || p[1] == '\\\\')) p.remove_prefix(2);\n";
    out << "        if (p.rfind(prefix, 0) == 0) { lua_pushboolean(L, 1); return 1; }\n";
    out << "    }\n";
    out << "    lua_pushboolean(L, isDirectory(pathStr));\n";
    out << "    return 1;\n";
    out << "}\n\n";

    out << "static int embedded_fs_stat(lua_State* L)\n{\n";
    out << "    const char* pathStr = luaL_checkstring(L, 1);\n";
    out << "    const EmbeddedAssetRecord* asset = findEmbeddedAsset(pathStr);\n";
    out << "    if (asset)\n    {\n";
    out << "        lua_createtable(L, 0, 4);\n";
    out << "        lua_pushnumber(L, static_cast<double>(asset->size)); lua_setfield(L, -2, \"size\");\n";
    out << "        lua_pushboolean(L, 1); lua_setfield(L, -2, \"is_file\");\n";
    out << "        lua_pushboolean(L, 0); lua_setfield(L, -2, \"is_dir\");\n";
    out << "        lua_pushnumber(L, 0); lua_setfield(L, -2, \"modified\");\n";
    out << "        return 1;\n";
    out << "    }\n";
    out << "    lua_getglobal(L, \"fs\");\n";
    out << "    if (lua_istable(L, -1))\n    {\n";
    out << "        lua_getfield(L, -1, \"stat\");\n";
    out << "        if (lua_iscfunction(L, -1))\n        {\n";
    out << "            lua_pushvalue(L, 1);\n";
    out << "            lua_call(L, 1, 1);\n";
    out << "            lua_remove(L, -2);\n";
    out << "            return 1;\n";
    out << "        }\n";
    out << "    }\n";
    out << "    luaL_error(L, \"fs.stat: cannot stat: %s\", pathStr);\n";
    out << "    return 0;\n";
    out << "}\n\n";

    // Main entry point
    out << "int main(int argc, char** argv)\n{\n";
    out << "    lua_State* L = luaL_newstate();\n";
    out << "    if (!L) { fprintf(stderr, \"Failed to initialize Luau VM\\n\"); return 1; }\n\n";
    if (enableCodegen)
    {
        out << "    if (Luau::CodeGen::isSupported())\n        Luau::CodeGen::create(L);\n\n";
    }
    out << "    luaL_openlibs(L);\n\n";

    out << "    // Inject embedded filesystem hooks\n";
    out << "    lua_getglobal(L, \"fs\");\n";
    out << "    if (lua_istable(L, -1))\n    {\n";
    out << "        lua_pushcfunction(L, embedded_fs_readfile, \"fs.readfile\");\n";
    out << "        lua_setfield(L, -2, \"readfile\");\n";
    out << "        lua_pushcfunction(L, embedded_fs_readfile, \"fs.readFile\");\n";
    out << "        lua_setfield(L, -2, \"readFile\");\n";
    out << "        lua_pushcfunction(L, embedded_fs_exists, \"fs.exists\");\n";
    out << "        lua_setfield(L, -2, \"exists\");\n";
    out << "        lua_pushcfunction(L, embedded_fs_isfile, \"fs.isfile\");\n";
    out << "        lua_setfield(L, -2, \"isfile\");\n";
    out << "        lua_pushcfunction(L, embedded_fs_isfile, \"fs.isFile\");\n";
    out << "        lua_setfield(L, -2, \"isFile\");\n";
    out << "        lua_pushcfunction(L, embedded_fs_isdir, \"fs.isdir\");\n";
    out << "        lua_setfield(L, -2, \"isdir\");\n";
    out << "        lua_pushcfunction(L, embedded_fs_isdir, \"fs.isDir\");\n";
    out << "        lua_setfield(L, -2, \"isDir\");\n";
    out << "        lua_pushcfunction(L, embedded_fs_stat, \"fs.stat\");\n";
    out << "        lua_setfield(L, -2, \"stat\");\n";
    out << "    }\n";
    out << "    lua_pop(L, 1);\n\n";

    out << "    EmbeddedRequireContext requireCtx;\n";
    out << "    luaopen_require(L, embeddedRequireConfigInit, &requireCtx);\n\n";

    // Setup arg table
    out << "    lua_createtable(L, argc, 0);\n";
    out << "    for (int i = 0; i < argc; ++i)\n    {\n";
    out << "        lua_pushstring(L, argv[i]);\n";
    out << "        lua_rawseti(L, -2, i);\n";
    out << "    }\n";
    out << "    lua_setglobal(L, \"arg\");\n\n";

    // Load entry point module
    out << "    const EmbeddedModuleRecord& entry = kEmbeddedModules[kEntryModuleIndex];\n";
    out << "    int status = luau_load(L, entry.chunkName, reinterpret_cast<const char*>(entry.bytecode), entry.bytecodeSize, 0);\n";
    out << "    if (status != 0)\n    {\n";
    out << "        fprintf(stderr, \"Error loading entry chunk: %s\\n\", lua_tostring(L, -1));\n";
    out << "        lua_close(L);\n";
    out << "        return 1;\n";
    out << "    }\n\n";
    if (enableCodegen)
    {
        out << "    if (Luau::CodeGen::isSupported())\n    {\n";
        out << "        Luau::CodeGen::CompilationOptions nativeOpts;\n";
        out << "        Luau::CodeGen::compile(L, -1, nativeOpts);\n";
        out << "    }\n\n";
    }
    out << "    // Run entry module passing argv as varargs\n";
    out << "    for (int i = 1; i < argc; ++i)\n        lua_pushstring(L, argv[i]);\n\n";
    out << "    status = lua_pcall(L, argc > 1 ? argc - 1 : 0, LUA_MULTRET, 0);\n";
    out << "    if (status != 0)\n    {\n";
    out << "        fprintf(stderr, \"Runtime error: %s\\n\", lua_tostring(L, -1));\n";
    out << "        lua_close(L);\n";
    out << "        return 1;\n";
    out << "    }\n\n";
    out << "    lua_close(L);\n";
    out << "    return 0;\n";
    out << "}\n";

    return out.str();
}

} // namespace

bool SingleBinaryCompiler::compile(const SingleBinaryOptions& options)
{
    if (options.entryFilePath.empty())
    {
        fprintf(stderr, "SingleBinaryCompiler: No entry file specified\n");
        return false;
    }

    std::string entryAbsPath = normalizePath(options.entryFilePath);
    if (!isAbsolutePath(entryAbsPath))
    {
        if (auto cwd = getCurrentWorkingDirectory())
            entryAbsPath = normalizePath(*cwd + "/" + entryAbsPath);
    }

    std::optional<std::string> entrySource = readFile(entryAbsPath);
    if (!entrySource)
    {
        fprintf(stderr, "SingleBinaryCompiler: Cannot read entry file '%s'\n", entryAbsPath.c_str());
        return false;
    }

    // Traverse Luau module dependencies
    std::vector<DiscoveredModule> modules;
    std::set<std::string> visitedAbsPaths;
    std::queue<std::string> toVisit;

    toVisit.push(entryAbsPath);
    visitedAbsPaths.insert(entryAbsPath);

    Luau::CompileOptions copts;
    copts.optimizationLevel = options.optimizationLevel;
    copts.debugLevel = options.debugLevel;

    size_t entryIndex = 0;

    while (!toVisit.empty())
    {
        std::string currentPath = toVisit.front();
        toVisit.pop();

        std::optional<std::string> source = readFile(currentPath);
        if (!source)
        {
            fprintf(stderr, "SingleBinaryCompiler: Warning: Could not read module '%s'\n", currentPath.c_str());
            continue;
        }

        std::string bytecode = Luau::compile(*source, copts);

        DiscoveredModule mod;
        mod.absolutePath = currentPath;
        mod.loadName = currentPath;
        mod.chunkName = "@" + currentPath;
        mod.source = *source;
        mod.bytecode = bytecode;

        if (currentPath == entryAbsPath)
            entryIndex = modules.size();

        modules.push_back(mod);

        // Parse AST to find require() calls
        Luau::Allocator allocator;
        Luau::AstNameTable names(allocator);
        Luau::ParseOptions popts;
        Luau::ParseResult parseResult = Luau::Parser::parse(source->data(), source->size(), names, allocator, popts);
        if (parseResult.root)
        {
            RequireVisitor visitor;
            parseResult.root->visit(&visitor);

            for (const std::string& reqPath : visitor.requirePaths)
            {
                // Skip built-in virtual standard library modules
                if (reqPath.rfind("@std/", 0) == 0 || reqPath == "@std")
                    continue;

                // Resolve target path
                std::string target = reqPath;
                std::string resolvedTarget;

                if (target.size() >= 2 && target.substr(0, 2) == "./")
                {
                    if (auto parent = getParentPath(currentPath))
                        resolvedTarget = normalizePath(*parent + "/" + target.substr(2));
                }
                else if (target.size() >= 3 && target.substr(0, 3) == "../")
                {
                    if (auto parent = getParentPath(currentPath))
                        resolvedTarget = normalizePath(*parent + "/" + target);
                }
                else if (!target.empty() && target[0] == '@')
                {
                    resolvedTarget = target;
                }
                else
                {
                    if (auto parent = getParentPath(currentPath))
                        resolvedTarget = normalizePath(*parent + "/" + target);
                }

                // Check potential extensions
                static const char* suffixes[] = {"", ".luau", ".lua", "/init.luau", "/init.lua", "/index.luau", "/index.lua"};
                for (const char* suf : suffixes)
                {
                    std::string cand = resolvedTarget + suf;
                    if (isFile(cand))
                    {
                        if (visitedAbsPaths.find(cand) == visitedAbsPaths.end())
                        {
                            visitedAbsPaths.insert(cand);
                            toVisit.push(cand);
                        }
                        break;
                    }
                }
            }
        }
    }

    // Traverse and collect asset files & directories
    std::vector<DiscoveredAsset> assets;
    std::set<std::string> visitedAssetPaths;

    auto addAssetFile = [&](const std::string& filePath, const std::string& relPath) {
        std::string absPath = normalizePath(filePath);
        if (!isAbsolutePath(absPath))
        {
            if (auto cwd = getCurrentWorkingDirectory())
                absPath = normalizePath(*cwd + "/" + absPath);
        }

        if (visitedAssetPaths.find(absPath) != visitedAssetPaths.end())
            return;
        visitedAssetPaths.insert(absPath);

        std::optional<std::string> content = readFile(absPath);
        if (!content)
        {
            fprintf(stderr, "SingleBinaryCompiler: Warning: Could not read asset '%s'\n", filePath.c_str());
            return;
        }

        DiscoveredAsset asset;
        asset.path = filePath;
        asset.relativePath = relPath;
        asset.absolutePath = absPath;
        asset.data = *content;
        assets.push_back(std::move(asset));
    };

    for (const std::string& assetSpec : options.assetPaths)
    {
        if (assetSpec.empty())
            continue;

        std::string resolved = assetSpec;
        if (!isAbsolutePath(resolved))
        {
            if (auto cwd = getCurrentWorkingDirectory())
                resolved = normalizePath(*cwd + "/" + resolved);
        }

        if (isFile(resolved))
        {
            addAssetFile(resolved, assetSpec);
        }
        else if (isDirectory(resolved))
        {
            traverseDirectory(resolved, [&](const std::string& filePath) {
                std::string rel = filePath;
                if (rel.size() >= resolved.size() && rel.substr(0, resolved.size()) == resolved)
                {
                    std::string sub = rel.substr(resolved.size());
                    if (!sub.empty() && (sub[0] == '/' || sub[0] == '\\'))
                        sub = sub.substr(1);
                    rel = normalizePath(assetSpec + "/" + sub);
                }
                addAssetFile(filePath, rel);
            });
        }
        else
        {
            fprintf(stderr, "SingleBinaryCompiler: Warning: Asset path '%s' not found\n", assetSpec.c_str());
        }
    }

    if (options.verbose)
    {
        printf("SingleBinaryCompiler: Bundled %zu module(s) and %zu asset(s) for entry '%s'\n",
               modules.size(), assets.size(), entryAbsPath.c_str());
        for (const auto& m : modules)
            printf("  [module] %s (%zu bytes bytecode)\n", m.absolutePath.c_str(), m.bytecode.size());
        for (const auto& a : assets)
            printf("  [asset]  %s (%zu bytes)\n", a.relativePath.c_str(), a.data.size());
    }

    std::string runnerCode = generateRunnerCpp(
        modules,
        entryIndex,
        assets,
        options.codegen,
        options.optimizationLevel,
        options.debugLevel
    );

    // Write temp runner source
    char tempPath[256];
    snprintf(tempPath, sizeof(tempPath), "/tmp/jaci_single_binary_%d.cpp", static_cast<int>(getpid()));

    FILE* fp = fopen(tempPath, "w");
    if (!fp)
    {
        fprintf(stderr, "SingleBinaryCompiler: Could not open temporary runner file '%s'\n", tempPath);
        return false;
    }
    fwrite(runnerCode.data(), 1, runnerCode.size(), fp);
    fclose(fp);

    // Locate include paths and build libraries
    std::string rootDir = "/home/klee/Documentos/jaci";
    if (const char* envRoot = getenv("JACI_ROOT"))
        rootDir = envRoot;

    std::string buildDir = rootDir + "/build";
    if (const char* envBuild = getenv("JACI_BUILD"))
        buildDir = envBuild;

    std::string outPath = options.outputBinaryPath.empty() ? "a.out" : options.outputBinaryPath;

    std::string compiler = "c++";
    std::string extraLinkerFlags = "-ldl -lpthread -lm";

    if (!options.targetArchitecture.empty())
    {
        const std::string& tgt = options.targetArchitecture;
        if (tgt == "linux-arm64" || tgt == "aarch64-linux" || tgt == "aarch64-linux-gnu" || tgt == "arm64")
        {
            compiler = "aarch64-linux-gnu-g++";
        }
        else if (tgt == "windows-x64" || tgt == "x86_64-w64-mingw32" || tgt == "win64" || tgt == "windows")
        {
            compiler = "x86_64-w64-mingw32-g++";
            extraLinkerFlags = "-lws2_32 -lbcrypt";
        }
        else if (tgt == "linux-x64" || tgt == "x86_64-linux" || tgt == "x86_64-linux-gnu" || tgt == "x64")
        {
            compiler = "x86_64-linux-gnu-g++";
        }
        else if (tgt == "macos-arm64" || tgt == "darwin-arm64")
        {
            compiler = "clang++ -target arm64-apple-macos";
            extraLinkerFlags = "-framework CoreFoundation -lpthread -lm";
        }
        else if (tgt == "macos-x64" || tgt == "darwin-x64")
        {
            compiler = "clang++ -target x86_64-apple-macos";
            extraLinkerFlags = "-framework CoreFoundation -lpthread -lm";
        }
        else
        {
            compiler = tgt;
        }
    }

    // Verify if compiler binary is available in PATH
    std::string compilerBinary = compiler;
    size_t spacePos = compilerBinary.find(' ');
    if (spacePos != std::string::npos)
        compilerBinary = compilerBinary.substr(0, spacePos);

    std::string checkCmd = "command -v " + compilerBinary + " >/dev/null 2>&1";
    if (system(checkCmd.c_str()) != 0)
    {
        if (options.targetArchitecture == "linux-x64" || options.targetArchitecture == "x64" || options.targetArchitecture.empty())
        {
            compiler = "c++";
        }
        else
        {
            fprintf(stderr, "SingleBinaryCompiler: Toolchain compiler '%s' not found in PATH for target '%s'.\n",
                    compilerBinary.c_str(), options.targetArchitecture.c_str());
            fprintf(stderr, "Please install the required cross-compilation toolchain or specify a custom compiler command via --target=<compiler>.\n");
            unlink(tempPath);
            return false;
        }
    }

    std::ostringstream cmd;
    cmd << compiler << " -std=c++17 -O2 "
        << "-I" << rootDir << "/VM/include "
        << "-I" << rootDir << "/Common/include "
        << "-I" << rootDir << "/Ast/include "
        << "-I" << rootDir << "/Compiler/include "
        << "-I" << rootDir << "/CodeGen/include "
        << "-I" << rootDir << "/Inliner/include "
        << "-I" << rootDir << "/Config/include "
        << "-I" << rootDir << "/Require/include "
        << "-I" << rootDir << "/CLI/include "
        << "-I" << rootDir << "/extern/isocline/include "
        << tempPath << " "
        << "-o " << outPath << " "
        << "-L" << buildDir << " "
        << "-Wl,--start-group "
        << "-lLuau.CLI.lib -lLuau.Require -lLuau.CodeGen -lLuau.Compiler "
        << "-lLuau.Bytecode -lLuau.Inliner -lLuau.VM -lLuau.Config -lLuau.Analysis -lLuau.Ast -lLuau.Common "
        << "-lisocline "
        << "-Wl,--end-group "
        << extraLinkerFlags;

    if (options.verbose)
        printf("SingleBinaryCompiler: Executing: %s\n", cmd.str().c_str());

    int ret = system(cmd.str().c_str());
    unlink(tempPath);

    if (ret != 0)
    {
        fprintf(stderr, "SingleBinaryCompiler: C++ compilation failed with exit code %d\n", ret);
        return false;
    }

    if (options.verbose)
        printf("SingleBinaryCompiler: Successfully generated standalone binary '%s'\n", outPath.c_str());

    return true;
}

} // namespace Luau
